"""gen_allow: derive the allow-list of source directories from project.xml."""
from __future__ import annotations
from typing import List, Tuple
from lxml import etree


def project_sources(project_xml: str) -> List[Tuple[str, str]]:
    root = etree.parse(project_xml).getroot()
    out = []
    for s in root.iter("source"):
        out.append((s.get("name"), s.get("type") or s.get("name")))
    return out


def allow_tokens(project_xml: str) -> List[str]:
    toks = []
    for name, typ in project_sources(project_xml):
        for t in (name, typ):
            tok = f"/{t}/"
            if tok not in toks:
                toks.append(tok)
    return toks


def write_allow(project_xml: str, out_path: str) -> List[str]:
    toks = allow_tokens(project_xml)
    with open(out_path, "w") as fh:
        fh.write("# path tokens of additions/keys dirs that belong to project.xml sources\n")
        fh.write("# (generated by `rdfc2im allow`; core.xml + genomic_additions.xml load unconditionally)\n")
        for t in toks:
            fh.write(t + "\n")
    return toks
