"""Generate the per-table SPARQL queries and the `humanmine*:` blocks of sparql.yaml.

Only the identifier rows (required=yes) are required triple patterns; everything else is
OPTIONAL, so a predicate that is absent for some entities does not drop them (this replaces
the spec's `optionalize_model` step).  Each table is its own query: the root's key columns
plus the table's own columns, so multi-valued predicates never cross-multiply.
"""
from __future__ import annotations
import os
import re
import shutil
from typing import Dict, List, Optional, Tuple

import yaml

from .mapping import Node, LOADABLE

VERSION_LINE = "# Generated by rdfc2im - do not edit; edit mapping_predicates.sssom.tsv and re-run"


def table_names(rows: List[dict]) -> List[str]:
    out = []
    for r in rows:
        t = r.get("table", "")
        if t and t not in ("*", "drop") and t not in out and r.get("status") in LOADABLE:
            out.append(t)
    return out


def query_rows(rows: List[dict], table: str, include_guess: bool) -> List[dict]:
    ok = {"sure", "human"} | ({"guess"} if include_guess else set())
    own = [r for r in rows if r.get("table") == table and r.get("status") in ok
           and r.get("im_class") and r.get("im_field") and r.get("kind") != "const"]
    req = [r for r in rows if r.get("required") == "yes" and r.get("status") in ok
           and r.get("im_class") and r.get("im_field") and r.get("kind") != "const"
           and r.get("table") not in ("*", "drop")]
    if own and all(r.get("required") == "yes" for r in own) and table != "main":
        return []          # nothing beyond the key columns: redundant table
    seen, out = set(), []
    for r in req + own:
        k = (r["subject"], r["predicate"], r["column"])
        if k in seen:
            continue
        seen.add(k)
        out.append(r)
    return out


def const_rows(rows: List[dict], table: str, include_guess: bool) -> List[dict]:
    ok = {"sure", "human"} | ({"guess"} if include_guess else set())
    return [r for r in rows if r.get("kind") == "const" and r.get("status") in ok
            and r.get("table") in (table, "*")]


class QueryBuilder:
    def __init__(self, cfg, node_by_key: Dict[Tuple[str, str, str], Node], types: str = "root",
                 distinct: bool = True, use_from: bool = True):
        self.cfg = cfg
        self.node_by_key = node_by_key
        self.types = types
        self.distinct = distinct
        self.use_from = use_from
        self.messages: List[str] = []

    def build(self, table: str, qrows: List[dict], limit: int = 0) -> Tuple[str, List[str], Dict[str, str]]:
        """Return (sparql, select_vars_in_order, parameters).

        `self.kept` is set to the rows actually selected, in SELECT order, one per variable.
        Pair columns with variables through it: a row skipped here (a link with no single
        variable) would otherwise shift every later column onto the wrong variable.
        """
        self.kept = []
        # leaves per node
        leaves: Dict[str, List[dict]] = {}
        nodes: Dict[str, Node] = {}
        root: Optional[Node] = None
        used_vars: Dict[str, int] = {}
        kept: List[dict] = []
        select: List[str] = []
        params: Dict[str, str] = {}
        for r in qrows:
            node = self.node_by_key.get((r["subject"], r["predicate"], r["column"]))
            if node is None:
                self.messages.append(f"{table}: row {r['subject']}/{r['predicate']}/{r['column']} has no node (stale?) - skipped")
                continue
            root = node.root
            var = r["column"]
            if r.get("kind") == "link":
                # the object IS a sub-node; use that node's variable
                child = next((c for c in node.children if c.objvar == r["column"]), None)
                if child is None or child.union:
                    why = "a union object ([A, B, ...]) has no single variable" if child is not None \
                        else "no sub-node binds it"
                    self.messages.append(f"{table}: link row {r['column']} cannot be a column ({why}) - skipped")
                    continue
                var = child.var
            if var in used_vars:
                used_vars[var] += 1
                var = f"{var}{used_vars[var]}"
            else:
                used_vars[var] = 1
            r = dict(r); r["_var"] = var
            leaves.setdefault(node.display, []).append(r)
            kept.append(r)
            n = node
            while n is not None:
                nodes[n.display] = n
                n = n.parent
            select.append(var)
            if r.get("value"):
                params[var] = r["value"]
        if root is None:
            return "", [], {}
        # query_rows() drops a satellite table that has nothing but the root's key columns, but a
        # row can also be skipped above (a link with no node to bind to).  If that leaves only the
        # key columns, the query is a projection of `main` and carries nothing; don't emit it.
        if table != "main" and all(r.get("required") == "yes" for r in kept):
            self.messages.append(f"{table}: nothing left but the root key after skips - table dropped")
            return "", [], {}
        self.kept = kept

        body = self._emit(root, nodes, leaves, indent=1)
        curies = set(re.findall(r"(?<![<\w])([A-Za-z][\w.-]*):(?=[^\s/])", "\n".join(body)))
        prefixes = []
        for p in sorted(curies):
            if p in self.cfg.prefixes:
                prefixes.append(f"PREFIX {p}: <{self.cfg.prefixes[p]}>")
            elif p not in ("http", "https", "urn", "mailto"):
                self.messages.append(f"{table}: prefix '{p}' is not in prefix.yaml")
        froms = [f"FROM <{g}>" for g in (self.cfg.graphs if self.use_from else [])]
        head = [f"# Source: {self.cfg.name}", f"# Table: {table}", f"# Endpoint: {self.cfg.endpoint or '(none in endpoint.yaml)'}",
                VERSION_LINE, ""]
        sel = "SELECT " + ("DISTINCT " if self.distinct else "") + " ".join(f"?{v}" for v in select)
        q = "\n".join(head + prefixes + ["", sel] + froms + ["WHERE {"] + body + ["}"]
                      + ([f"LIMIT {limit}"] if limit else []))
        return q + "\n", select, params

    UNTYPED = {"http://www.w3.org/2000/01/rdf-schema#Resource", "http://www.w3.org/2002/07/owl#Thing"}

    def _type_triple(self, node: Node) -> List[str]:
        # rdf-config writes `a: rdfs:Resource` when a subject has no useful type; no data carries that triple
        types = [t for t in node.subject.types if self.cfg.expand(t) not in self.UNTYPED]
        if not types:
            return []
        want = node.parent is None or node.union or self.types == "all"
        if not want:
            return []
        return [f"?{node.var} a {types[0]} ."]   # first type is the specific one by convention

    def _emit(self, node: Node, nodes: Dict[str, Node], leaves: Dict[str, List[dict]], indent: int) -> List[str]:
        pad = "  " * indent
        lines: List[str] = []
        if node.parent is not None:
            lines.append(f"{pad}?{node.parent.var} {node.pred.curie} ?{node.var} .")
        lines += [pad + t for t in self._type_triple(node)]
        own = [r for r in leaves.get(node.display, []) if r.get("predicate") != "-self-"]
        # a link column whose sub-node is emitted below is bound there already
        own = [r for r in own if not (r.get("kind") == "link" and any(c.display in nodes and c.objvar == r["column"] for c in node.children))]
        for r in own:
            if r.get("required") == "yes":
                lines.append(f"{pad}?{node.var} {r['predicate']} ?{r['_var']} .")
                if r.get("value"):
                    lines.append(f"{pad}{_constraint(r['_var'], r['value'])}")
        for r in own:
            if r.get("required") != "yes":
                extra = f" {_constraint(r['_var'], r['value'])}" if r.get("value") else ""
                lines.append(f"{pad}OPTIONAL {{ ?{node.var} {r['predicate']} ?{r['_var']} .{extra} }}")
        for child in node.children:
            if child.display not in nodes:
                continue
            if self._required(child, leaves):
                lines += self._emit(child, nodes, leaves, indent)
            else:
                lines.append(f"{pad}OPTIONAL {{")
                lines += self._emit(child, nodes, leaves, indent + 1)
                lines.append(f"{pad}}}")
        return lines

    def _required(self, node: Node, leaves) -> bool:
        if any(r.get("required") == "yes" for r in leaves.get(node.display, [])):
            return True
        return any(self._required(c, leaves) for c in node.children)


def _constraint(var: str, value: str) -> str:
    """A quoted literal is compared by string value (typed literals would not match a plain
    VALUES); IRIs/CURIEs/numbers use VALUES."""
    v = value.strip()
    if v.startswith('"'):
        return f'FILTER(STR(?{var}) = {v})'
    return f"VALUES ?{var} {{ {v} }}"


# ------------------------------------------------------------------ sparql.yaml
def write_sparql_yaml(cfg, out_dir: str, blocks: Dict[str, dict]):
    """out/<src>/sparql.yaml = committed_sparql.yaml (pristine snapshot) + humanmine blocks."""
    committed = os.path.join(out_dir, "committed_sparql.yaml")
    src_yaml = os.path.join(cfg.dir, "sparql.yaml")
    if not os.path.exists(committed):
        if os.path.exists(src_yaml):
            shutil.copy(src_yaml, committed)
        else:
            open(committed, "w").close()
    with open(committed, encoding="utf-8", errors="replace") as fh:
        base = fh.read().rstrip("\n")
    gen = yaml.safe_dump(blocks, sort_keys=False, allow_unicode=True, width=1000, default_flow_style=None)
    with open(os.path.join(out_dir, "sparql.yaml"), "w", encoding="utf-8") as fh:
        if base:
            fh.write(base + "\n")
        fh.write("\n# ---- generated by rdfc2im (cross-check: `rdf-config --config <copy> --sparql humanmine`) ----\n")
        fh.write(gen)


def yaml_block(table: str, select: List[str], params: Dict[str, str], limit: int, cfg) -> dict:
    b = {"description": f"HumanMine extract of {cfg.name} - table {table} (rdfc2im)",
         "variables": list(select)}
    if params:
        b["parameters"] = dict(params)
    opts = {"distinct": True}
    if limit:
        opts["limit"] = limit
    b["options"] = opts
    return b


def block_name(table: str) -> str:
    return "humanmine" if table == "main" else f"humanmine_{table}"
